//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace herbDllProj
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class herbals
    {
        public int id { get; set; }
        public string name_latin { get; set; }
        public string name_russian {get; set;}       
        public string description { get; set; }
        public string advantages { get; set; }
        public string herbal_using { get; set; }
        public string receipsTxt { get; set; }
        public string additional_info { get; set; }
        public string places { get; set; }
        public string preparing { get; set; }
    }
}
